name: Build

on:
  pull_request:
  push:
    branches:
      - 'master'
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        label:
          - Stable
          - Unstable
          - Unknown
        include:
          - label: Stable
            postfix: _stable
            target: wasm32-wasip1
            features: '""'
          - label: Unstable
            postfix: _unstable
            target: wasm32-wasip1
            features: '"unstable"'
          - label: Unknown
            postfix: _unknown
            target: wasm32-unknown-unknown
            features: '""'
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Install Rust
        uses: hecrj/setup-rust-action@v2
        with:
          rust-version: stable
          targets: ${{matrix.target}}

      - name: Build
        run: |
          cargo release --locked --target ${{matrix.target}} --features ${{ matrix.features }}

      - name: Prepare Release
        run: |
          cp target/${{matrix.target}}/release/hollowknight_autosplit_wasm.wasm hollowknight_autosplit_wasm${{ matrix.postfix }}.wasm

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: hollowknight_autosplit_wasm*.wasm

  clippy:
    name: Check clippy lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Install Rust
        uses: hecrj/setup-rust-action@v2
        with:
          components: clippy
          targets: wasm32-wasip1

      - name: Run Clippy
        run: cargo clippy --all-features

  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Install Rust
        uses: hecrj/setup-rust-action@v2
        with:
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt -- --check || true
