name: Build

on:
  pull_request:
  push:
    branches:
      - 'master'
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        label:
          - Stable
          - Unstable
        include:
          - label: Stable
            postfix: _stable
            features: '""'
          - label: Unstable
            postfix: _unstable
            features: '"unstable"'
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3

      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
          targets: wasm32-wasi

      - name: Build
        run: |
          cargo release --locked --features ${{ matrix.features }}

      - name: Prepare Release
        run: |
          cp target/wasm32-wasi/release/hollowknight_autosplit_wasm.wasm hollowknight_autosplit_wasm${{ matrix.postfix }}.wasm

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: hollowknight_autosplit_wasm*.wasm

  clippy:
    name: Check clippy lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3

      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: clippy
          targets: wasm32-wasi

      - name: Run Clippy
        run: cargo clippy --all-features

  format:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3

      - name: Install Rust
        uses: hecrj/setup-rust-action@v1
        with:
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt -- --check || true
